// supabase/functions/_shared/engine/catalog/mca.ts
import { addMonths, firstFinancialYearEnd, utcDate, formatDate } from '../../dates.ts';
import {
  CRORE,
  acceptsDeposits,
  anyOf,
  buysFromMsmeSuppliers,
  custom,
  entityIs,
  hasDirectorWithDin,
  isCompaniesActEntity,
  llpCrossesAuditThreshold,
  paidUpCapitalAtLeast,
  turnoverAtLeast,
} from '../conditions.ts';
import {
  annual,
  annualFromAgm,
  dateAfterFy,
  halfYearly,
  oneTimeFromIncorporation,
  quarterly,
} from '../schedule.ts';
import type { ComplianceRule } from '../types.ts';

const isSmallCompany = custom(
  'Qualifies as a small company (capital ≤ ₹4 crore and turnover ≤ ₹40 crore)',
  (ctx) =>
    ['PRIVATE_LIMITED'].includes(ctx.company.entityType) &&
    ctx.company.paidUpCapital <= 4 * CRORE &&
    ctx.company.annualTurnover <= 40 * CRORE,
);

const isNotSmallCompany = custom(
  'Is not a small company (files the full annual return, MGT-7)',
  (ctx) => !isSmallCompany.test(ctx),
);

const incorporatedAfterInc20aCommencement = custom(
  'Incorporated on or after 2 November 2018',
  (ctx) => Boolean(ctx.company.incorporationDate && ctx.company.incorporationDate >= utcDate(2018, 11, 2)),
);

export const mcaRules: ComplianceRule[] = [
  {
    code: 'MCA_AOC4',
    title: 'File financial statements (AOC-4)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'AOC-4',
    legalReference: 'Section 137, Companies Act 2013',
    description:
      'File the audited balance sheet, profit & loss account, board report and auditor report with the Registrar within 30 days of the AGM.',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit, plus penalties on the company and every officer in default.',
    evidenceRequired: ['Audited financial statements', 'Board report', 'Auditor report', 'AOC-4 filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'SECTION_8')],
    occurrences: annualFromAgm({ offsetDays: 30, fallback: { month: 10, day: 30 } }),
  },
  {
    code: 'MCA_AOC4_OPC',
    title: 'File financial statements (AOC-4) — One Person Company',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'AOC-4',
    legalReference: 'Section 137(1) proviso, Companies Act 2013',
    description:
      'An OPC holds no AGM, so AOC-4 is due within 180 days of the close of the financial year.',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit.',
    evidenceRequired: ['Audited financial statements', 'Auditor report', 'AOC-4 filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('OPC')],
    occurrences: (fy) => [
      {
        periodKey: fy.key,
        periodLabel: fy.label,
        periodStart: fy.start,
        periodEnd: fy.end,
        dueDate: new Date(fy.end.getTime() + 180 * 86_400_000),
      },
    ],
  },
  {
    code: 'MCA_MGT7',
    title: 'File annual return (MGT-7)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'MGT-7',
    legalReference: 'Section 92, Companies Act 2013',
    description:
      'File the annual return covering shareholding, directors, meetings and indebtedness within 60 days of the AGM.',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit. Company and officers face penalties up to ₹5,00,000.',
    evidenceRequired: ['Signed MGT-7', 'List of shareholders', 'MGT-8 certificate (where applicable)', 'Filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'SECTION_8'), isNotSmallCompany],
    occurrences: annualFromAgm({ offsetDays: 60, fallback: { month: 11, day: 28 } }),
  },
  {
    code: 'MCA_MGT7A',
    title: 'File abridged annual return (MGT-7A)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'MGT-7A',
    legalReference: 'Section 92 read with Rule 11(1), Companies (Management and Administration) Rules 2014',
    description:
      'One Person Companies and small companies file the abridged annual return MGT-7A within 60 days of the AGM (or of the date the AGM ought to have been held).',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit.',
    evidenceRequired: ['Signed MGT-7A', 'List of shareholders', 'Filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [anyOf('Is an OPC or a small company', entityIs('OPC'), isSmallCompany)],
    occurrences: annualFromAgm({ offsetDays: 60, fallback: { month: 11, day: 28 } }),
  },
  {
    code: 'MCA_ADT1',
    title: 'Intimate auditor appointment (ADT-1)',
    authority: 'MCA',
    category: 'Audit',
    form: 'ADT-1',
    legalReference: 'Section 139, Companies Act 2013',
    description:
      'File ADT-1 within 15 days of the AGM at which the auditor is appointed or reappointed. An auditor appointed for a five-year term needs only one filing — mark this waived in the intervening years.',
    severity: 'HIGH',
    penalty: 'Additional fees on a sliding scale up to 12x the normal fee; the appointment remains unregistered.',
    evidenceRequired: ['Board/AGM resolution', "Auditor's written consent and eligibility certificate", 'ADT-1 challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: annualFromAgm({ offsetDays: 15, fallback: { month: 10, day: 14 } }),
  },
  {
    code: 'MCA_DIR3KYC',
    title: 'Director KYC (DIR-3 KYC)',
    authority: 'MCA',
    category: 'Director compliance',
    form: 'DIR-3 KYC / DIR-3 KYC-WEB',
    legalReference: 'Rule 12A, Companies (Appointment and Qualification of Directors) Rules 2014',
    description:
      'Every person holding a DIN or DPIN as on 31 March must complete KYC by 30 September of the same year. Use the web service if nothing has changed since last year.',
    severity: 'CRITICAL',
    penalty: 'DIN is deactivated and a flat ₹5,000 fee per director is charged to reactivate it.',
    evidenceRequired: ['DIR-3 KYC acknowledgement per director', 'PAN and Aadhaar copies', 'Digital signature certificate'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'ANNUAL',
    applicableWhen: [hasDirectorWithDin()],
    occurrences: annual({ month: 9, day: 30 }),
  },
  {
    code: 'MCA_DPT3',
    title: 'Return of deposits (DPT-3)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'DPT-3',
    legalReference: 'Rule 16, Companies (Acceptance of Deposits) Rules 2014',
    description:
      'Report outstanding loans and money received that are not treated as deposits, as at 31 March, by 30 June.',
    severity: 'HIGH',
    penalty: '₹5,000 plus ₹500 for each day the default continues.',
    evidenceRequired: ['Auditor certificate on outstanding balances', 'DPT-3 challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'ANNUAL',
    applicableWhen: [isCompaniesActEntity(), acceptsDeposits()],
    occurrences: annual({ month: 6, day: 30 }),
  },
  {
    code: 'MCA_MSME1',
    title: 'Half-yearly return for MSME dues (MSME-1)',
    authority: 'MCA',
    category: 'MSME reporting',
    form: 'MSME-1 (Form I)',
    legalReference: 'Section 405, Companies Act 2013 read with the MSME Development Act 2006',
    description:
      'Report payments to micro and small enterprise suppliers outstanding for more than 45 days. Due 31 October for April–September and 30 April for October–March.',
    severity: 'HIGH',
    penalty: 'Penalty up to ₹25,000 on the company and ₹25,000 to ₹3,00,000 on every officer in default.',
    evidenceRequired: ['Ageing report of MSME creditors', 'Udyam certificates of suppliers', 'MSME-1 challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'HALF_YEARLY',
    applicableWhen: [isCompaniesActEntity(), buysFromMsmeSuppliers()],
    occurrences: halfYearly({
      due: (_p, fy, i) => (i === 0 ? utcDate(fy.startYear, 10, 31) : dateAfterFy(fy, 4, 30)),
    }),
  },
  {
    code: 'MCA_DIR12',
    title: 'Intimate director/KMP change (DIR-12)',
    authority: 'MCA',
    category: 'Governance',
    form: 'DIR-12',
    legalReference: 'Sections 7(1)(c), 168 and 170(2), Companies Act 2013 read with Rule 17 of the Companies (Appointment and Qualification of Directors) Rules, 2014',
    description:
      'File DIR-12 within 30 days of any director or KMP appointment, cessation, or change in designation.',
    severity: 'CRITICAL',
    penalty: '₹3,00,000 for the company and ₹1,00,000 for the officer in default.',
    evidenceRequired: ['Board resolution approving appointment/change', 'DIR-2 (written consent of appointee)', 'DIR-8 (declaration of non-disqualification)'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'EVENT_BASED',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: (_fy, ctx) => {
      const events = (ctx.company.events || []).filter((e: any) => e.eventType === 'DIR-12');
      return events.map((e: any) => ({
        periodKey: `${ctx.company.id}-DIR12-${e.eventDate}-${new Date(e.eventDate.getTime() + 30 * 86400000).getTime()}`,
        periodLabel: `DIR-12: ${formatDate(new Date(e.eventDate.getTime() + 30 * 86400000))}`,
        periodStart: new Date(e.eventDate.getTime()),
        periodEnd: new Date(e.eventDate.getTime() + 30 * 86400000),
        dueDate: new Date(e.eventDate.getTime() + 30 * 86400000),
        metadata: { event: e, ruleCode: 'MCA_DIR12' },
      }));
    },
  },
  {
    code: 'MCA_PAS3',
    title: 'File return of allotment (PAS-3)',
    authority: 'MCA',
    category: 'MSME reporting',
    form: 'PAS-3',
    legalReference: 'Sections 39(4) and 42(9), Companies Act 2013',
    description: 'File PAS-3 within 30 days of the date of allotment of shares or other securities.',
    severity: 'HIGH',
    penalty: '₹1,000 per day or ₹1 lakh, whichever is less.',
    evidenceRequired: ['Board resolution approving allotment', 'List of allottees'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'EVENT_BASED',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: (_fy, ctx) => {
      const events = (ctx.company.events || []).filter((e: any) => e.eventType === 'PAS-3');
      return events.map((e: any) => ({
        periodKey: `${ctx.company.id}-PAS3-${e.eventDate}-${new Date(e.eventDate.getTime() + 30 * 86400000).getTime()}`,
        periodLabel: `PAS-3: ${formatDate(new Date(e.eventDate.getTime() + 30 * 86400000))}`,
        periodStart: new Date(e.eventDate.getTime()),
        periodEnd: new Date(e.eventDate.getTime() + 30 * 86400000),
        dueDate: new Date(e.eventDate.getTime() + 30 * 86400000),
        metadata: { event: e, ruleCode: 'MCA_PAS3' },
      }));
    },
  },
  {
    code: 'MCA_CHG1',
    title: 'Intimation of charge creation/modification (CHG-1)',
    authority: 'MCA',
    category: 'Governance',
    form: 'CHG-1',
    legalReference: 'Sections 77, 78 and 79, Companies Act 2013',
    description: 'File CHG-1 within 30 days of the creation or modification of a charge on company assets.',
    severity: 'CRITICAL',
    penalty: 'Additional fees escalating with delay.',
    evidenceRequired: ['Instrument creating/modifying the charge', 'Board resolution'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'EVENT_BASED',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: (_fy, ctx) => {
      const events = (ctx.company.events || []).filter((e: any) => e.eventType === 'CHG-1');
      return events.map((e: any) => ({
        periodKey: `${ctx.company.id}-CHG1-${e.eventDate}-${new Date(e.eventDate.getTime() + 30 * 86400000).getTime()}`,
        periodLabel: `CHG-1: ${formatDate(new Date(e.eventDate.getTime() + 30 * 86400000))}`,
        periodStart: new Date(e.eventDate.getTime()),
        periodEnd: new Date(e.eventDate.getTime() + 30 * 86400000),
        dueDate: new Date(e.eventDate.getTime() + 30 * 86400000),
        metadata: { event: e, ruleCode: 'MCA_CHG1' },
      }));
    },
  },
  {
    code: 'MCA_MGT14',
    title: 'File resolutions (MGT-14)',
    authority: 'MCA',
    category: 'Governance',
    form: 'MGT-14',
    legalReference: 'Section 117(1), Companies Act 2013',
    description: 'File MGT-14 within 30 days of passing a special resolution or specified board resolution.',
    severity: 'HIGH',
    penalty: 'Company: ₹1,00,000 + ₹500/day.',
    evidenceRequired: ['Certified true copy of the resolution'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'EVENT_BASED',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: (_fy, ctx) => {
      const events = (ctx.company.events || []).filter((e: any) => e.eventType === 'MGT-14');
      return events.map((e: any) => ({
        periodKey: `${ctx.company.id}-MGT14-${e.eventDate}-${new Date(e.eventDate.getTime() + 30 * 86400000).getTime()}`,
        periodLabel: `MGT-14: ${formatDate(new Date(e.eventDate.getTime() + 30 * 86400000))}`,
        periodStart: new Date(e.eventDate.getTime()),
        periodEnd: new Date(e.eventDate.getTime() + 30 * 86400000),
        dueDate: new Date(e.eventDate.getTime() + 30 * 86400000),
        metadata: { event: e, ruleCode: 'MCA_MGT14' },
      }));
    },
  },
  {
    code: 'MCA_AGM',
    title: 'Hold the Annual General Meeting',
    authority: 'MCA',
    category: 'Governance',
    legalReference: 'Section 96, Companies Act 2013',
    description: 'Hold the AGM within six months of the financial year end.',
    severity: 'CRITICAL',
    penalty: 'Up to ₹1,00,000 on the company and every officer in default.',
    evidenceRequired: ['Notice of AGM', 'Attendance register', 'Signed AGM minutes'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'SECTION_8')],
    occurrences: (fy, ctx) => {
      const incorporatedOn = ctx.company.incorporationDate;
      const isFirstAgm =
        incorporatedOn !== null && fy.end.getTime() === firstFinancialYearEnd(incorporatedOn).getTime();
      return [
        {
          periodKey: fy.key,
          periodLabel: fy.label,
          periodStart: fy.start,
          periodEnd: fy.end,
          dueDate: isFirstAgm ? addMonths(fy.end, 9) : dateAfterFy(fy, 9, 30),
          ...(isFirstAgm ? { metadata: { firstAgm: true } } : {}),
        },
      ];
    },
  },
  {
    code: 'MCA_BOARD_MEETING',
    title: 'Hold a board meeting for the quarter',
    authority: 'MCA',
    category: 'Governance',
    legalReference: 'Section 173, Companies Act 2013',
    description: 'Hold at least four board meetings a year with no more than 120 days between consecutive meetings.',
    severity: 'MEDIUM',
    penalty: '₹25,000 on the company and ₹5,000 on every officer in default.',
    evidenceRequired: ['Notice of board meeting', 'Signed board minutes'],
    evidenceLevel: 'ATTEST',
    signatoryRequired: true,
    periodKind: 'QUARTERLY',
    applicableWhen: [isCompaniesActEntity()],
    excludeWhen: [entityIs('OPC'), isSmallCompany],
    occurrences: quarterly({ due: (p) => p.end }),
  },
  {
    code: 'MCA_BOARD_MEETING_SMALL',
    title: 'Hold a board meeting for the half-year',
    authority: 'MCA',
    category: 'Governance',
    legalReference: 'Section 173(5), Companies Act 2013',
    description: 'One Person Companies and small companies must hold at least one board meeting in each half of the calendar year.',
    severity: 'MEDIUM',
    penalty: '₹25,000 on the company and ₹5,000 on every officer in default.',
    evidenceRequired: ['Notice of board meeting', 'Signed board minutes'],
    evidenceLevel: 'ATTEST',
    signatoryRequired: true,
    periodKind: 'HALF_YEARLY',
    applicableWhen: [anyOf('Is an OPC or a small company', entityIs('OPC'), isSmallCompany)],
    occurrences: halfYearly({ due: (p) => p.end }),
  },
  {
    code: 'MCA_MBP1',
    title: 'Collect directors’ disclosure of interest (MBP-1 and DIR-8)',
    authority: 'MCA',
    category: 'Governance',
    legalReference: 'Sections 184(1) and 164(2), Companies Act 2013',
    description: 'Every director discloses their interest in Form MBP-1 at the first board meeting of each financial year.',
    severity: 'MEDIUM',
    penalty: 'Penalty of ₹1,00,000 on the director concerned.',
    evidenceRequired: ['Signed MBP-1', 'Signed DIR-8'],
    evidenceLevel: 'ATTEST',
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [isCompaniesActEntity()],
    occurrences: annual({ month: 4, day: 30, anchor: 'within' }),
  },
  {
    code: 'MCA_INC20A',
    title: 'Declaration of commencement of business (INC-20A)',
    authority: 'MCA',
    category: 'Incorporation',
    form: 'INC-20A',
    legalReference: 'Section 10A, Companies Act 2013',
    description: 'File INC-20A within 180 days of incorporation.',
    severity: 'CRITICAL',
    penalty: '₹50,000 on the company and ₹1,000 per day on every officer.',
    evidenceRequired: ['Bank statement showing subscription money received', 'INC-20A challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    periodKind: 'ONE_TIME',
    applicableWhen: [
      entityIs('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'OPC'),
      paidUpCapitalAtLeast(1),
      incorporatedAfterInc20aCommencement,
    ],
    occurrences: oneTimeFromIncorporation({ withinDays: 180 }),
  },
  {
    code: 'LLP_FORM11',
    title: 'File LLP annual return (Form 11)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'Form 11',
    legalReference: 'Section 35, LLP Act 2008',
    description: 'File Form 11 within 60 days of the close of the financial year (by 30 May).',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit.',
    evidenceRequired: ['Signed Form 11', 'Filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('LLP')],
    occurrences: annual({ month: 5, day: 30 }),
  },
  {
    code: 'LLP_FORM8',
    title: 'File LLP statement of account and solvency (Form 8)',
    authority: 'MCA',
    category: 'Annual filing',
    form: 'Form 8',
    legalReference: 'Section 34(2), LLP Act 2008',
    description: 'File Form 8 by 30 October.',
    severity: 'CRITICAL',
    penalty: '₹100 per day of delay with no upper limit.',
    evidenceRequired: ['Statement of account and solvency', 'Filing challan (SRN)'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('LLP')],
    occurrences: annual({ month: 10, day: 30 }),
  },
  {
    code: 'LLP_AUDIT',
    title: 'Get the LLP accounts audited',
    authority: 'MCA',
    category: 'Audit',
    legalReference: 'Rule 24(8), LLP Rules 2009',
    description: 'Audited accounts required if turnover exceeds ₹40 lakh or contribution exceeds ₹25 lakh.',
    severity: 'HIGH',
    penalty: '₹25,000 to ₹5,00,000 on the LLP.',
    evidenceRequired: ['Audited financial statements', 'Auditor report'],
    evidenceLevel: 'REQUIRED',
    basedOnAnnualAccounts: true,
    signatoryRequired: true,
    periodKind: 'ANNUAL',
    applicableWhen: [entityIs('LLP'), llpCrossesAuditThreshold()],
    occurrences: annual({ month: 9, day: 30 }),
  },
];
