import { useEffect, useState } from 'react';
import { useCompanies } from '../auth/CompanyContext';
import { ApiError, post } from '../api/client';
import { useResource } from '../api/useResource';
import { Drawer, ErrorNote, Spinner } from './ui';
import type { CompanyMember, UserRole } from '../api/types';

/** Labels only. Which of these may actually be granted is the server's answer,
 *  not this file's — see invitePermission. */
const ROLE_LABELS: Record<string, { label: string; hint: string }> = {
  ADMIN: {
    label: 'Admin',
    hint: 'Runs this company: works the filings and can invite and remove people.',
  },
  COMPANY_OWNER: {
    label: 'Business owner',
    hint: "The client's own login — full control of this company, including its people.",
  },
  CA: {
    label: 'Chartered accountant',
    hint: "Works this company's tasks and filings, and can bring in other practitioners.",
  },
  VIEWER: {
    label: 'Viewer (read only)',
    hint: 'Can see the calendar, tasks and evidence, and change nothing.',
  },
};

interface InvitePermission {
  canInvite: boolean;
  roles: UserRole[];
  reason: string;
  inviterRole: UserRole | null;
}

/**
 * What an invite answers with.
 *
 * Every field is optional because two API implementations serve this endpoint
 * and they answered differently: one with { user, companies }, the other with a
 * member record. Reading result.user.role off the second threw a TypeError on a
 * request that had actually succeeded — so the invite worked, the member
 * appeared, and the form reported a crash.
 */
interface InviteResult {
  user?: { id: string; name: string; email: string; role: string };
  /** The older shape, kept readable rather than assumed away. */
  member?: { id: string; name: string; email: string; isActive?: boolean };
  role?: string;
  /** Generated by the server, shown once, and spent the first time it is used. */
  temporaryPassword?: string | null;
  companies: string[];
}

/**
 * Shared invite flow used from the Tasks assignee dropdown and the Companies
 * team list. Only CA and ADMIN are offered — never COMPANY_OWNER or SUPER_ADMIN.
 * The backend emails the invitee a signup link; the UI never shows a password.
 */
export function InviteMemberModal({ companyId, onInvited, onClose }: {
  companyId: string;
  onInvited?: (member: CompanyMember) => void;
  onClose: () => void;
}) {
  const { companies } = useCompanies();
  const company = companies.find((c) => c.id === companyId);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<UserRole | ''>('');
  /* What this user may actually grant here. Asked rather than assumed: a
     practitioner cannot grant Admin, and a dropdown that offers it produces a
     403 from a choice that should never have been on screen. */
  const { data: permission, error: permissionError } = useResource<InvitePermission>(
    `/companies/${companyId}/invite-permission`,
    [companyId],
  );
  /* Against an API without that endpoint, fall back to the roles every inviter
     is allowed to grant. Narrower than an owner is entitled to — Admin is
     missing — but the alternative is offering a role the server may refuse,
     which is the fault this replaced. The full list returns once companies-api
     ships the endpoint. */
  const grantable: UserRole[] = permission?.roles ?? (permissionError ? ['COMPANY_OWNER', 'CA', 'VIEWER'] : []);

  // Default to the first role they can grant, once we know what that is.
  useEffect(() => {
    if (!role && grantable.length) setRole(grantable[0]!);
  }, [grantable, role]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [doneEmail, setDoneEmail] = useState<string | null>(null);
  const [tempPassword, setTempPassword] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      const result = await post<InviteResult>(`/companies/${companyId}/invite`, { name, email, role });

      // Read whichever shape came back, and fall back to what was typed. The
      // invite has already happened by this point; nothing here is worth
      // failing a succeeded request over.
      const invited = result.user ?? result.member;
      const invitedEmail = invited?.email ?? email;

      onInvited?.({
        role: (result.user?.role ?? result.role ?? role) as UserRole,
        since: new Date().toISOString(),
        member: {
          id: invited?.id ?? '',
          name: invited?.name ?? name,
          email: invitedEmail,
          isActive: true,
        },
        invitedBy: { id: '', name: '' },
      });
      setDoneEmail(invitedEmail);
      setTempPassword(result.temporaryPassword ?? null);
    } catch (err) {
      // Say what the server said. "That did not work" hid a perfectly clear
      // "an account with this email already exists in your organisation".
      setError(
        err instanceof ApiError
          ? err.message
          : err instanceof Error && err.message
            ? err.message
            : 'That did not work',
      );
    } finally {
      setBusy(false);
    }
  }

  return (
    <Drawer onClose={onClose}>
      <header className="drawer-head">
        <div className="stack" style={{ flex: 1, gap: 4 }}>
          <h2 style={{ fontSize: 16 }}>Invite a team member</h2>
          <span className="tiny dim">
            {company ? `To ${company.legalName}` : 'To this company'}
          </span>
        </div>
        <button className="btn-ghost btn-sm" onClick={onClose}>✕</button>
      </header>

      <div className="drawer-body">
        {error && <ErrorNote error={error} />}

        {doneEmail ? (
          <div className="stack" style={{ gap: 12 }}>
            <div className="alert alert-info">
              <strong>{doneEmail} can now sign in.</strong>{' '}
              {tempPassword
                ? 'Give them the password below — it works once, and they must set their own before they can do anything.'
                : 'This server did not return a temporary password. If they cannot sign in, reset it for them from the team list.'}
            </div>

            {tempPassword && (
              <div className="field">
                <label>Temporary password</label>
                <div className="row" style={{ gap: 8 }}>
                  {/* Readable rather than masked: the point is to pass it on,
                      and hiding it only invites a screenshot. */}
                  <input readOnly value={tempPassword} onFocus={(e) => e.currentTarget.select()}
                         style={{ fontFamily: 'var(--mono)', letterSpacing: '0.04em' }} />
                  <button
                    className="btn-sm"
                    onClick={async () => {
                      try {
                        await navigator.clipboard.writeText(tempPassword);
                        setCopied(true);
                        setTimeout(() => setCopied(false), 2000);
                      } catch {
                        // Clipboard access can be refused; the field is selectable.
                        setCopied(false);
                      }
                    }}
                  >
                    {copied ? 'Copied' : 'Copy'}
                  </button>
                </div>
                <span className="field-hint">
                  This is the only time it is shown. Send it by a channel you trust.
                </span>
              </div>
            )}
          </div>
        ) : (
          <>
            <div className="field">
              <label>Name</label>
              <input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Priya Sharma"
                autoFocus
              />
            </div>
            <div className="field">
              <label>Email</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="priya@example.com"
              />
            </div>
            <div className="field">
              <label>Role</label>
              <select value={role} onChange={(e) => setRole(e.target.value as UserRole)} disabled={!grantable.length}>
                {grantable.map((r) => (
                  <option key={r} value={r}>{ROLE_LABELS[r]?.label ?? r}</option>
                ))}
              </select>
              <span className="field-hint">
                {role
                  ? ROLE_LABELS[role]?.hint
                  : permission
                    ? permission.reason || 'No roles are available for you to grant here.'
                    : permissionError
                      ? 'Showing the roles anyone may grant; this server cannot confirm the full list.'
                      : 'Checking what you can grant…'}
              </span>
            </div>
            <div className="row">
              <button
                className="btn-primary"
                disabled={busy || !role || name.trim().length < 2 || !email.includes('@')}
                onClick={submit}
              >
                {busy ? <><Spinner /> Sending…</> : 'Send invite'}
              </button>
              <button onClick={onClose}>Cancel</button>
            </div>
          </>
        )}
      </div>
    </Drawer>
  );
}
